#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Docker Integration for Website Creation
Enables the Website Creation Agent to build real websites using Docker
"""

import sys
import os
import json
import subprocess
import tempfile
import shutil
from pathlib import Path
import traceback
import time
import random
import string

class DockerWebsiteBuilder:
    """Builds real websites using Docker"""
    
    def __init__(self, docker_path="docker"):
        """Initialize the website builder
        
        Args:
            docker_path: Path to the docker executable
        """
        self.docker_path = docker_path
        self.websites_dir = Path("D:/AIArm/InnerLife/Generated/Websites")
        self.websites_dir.mkdir(exist_ok=True, parents=True)
        
        # Track active containers
        self.active_containers = {}
    
    def check_docker(self):
        """Check if Docker is installed and running"""
        try:
            # Check docker version
            result = subprocess.run(
                [self.docker_path, "--version"],
                capture_output=True,
                text=True,
                check=True
            )
            
            # Check if Docker daemon is running
            result = subprocess.run(
                [self.docker_path, "info"],
                capture_output=True,
                text=True,
                check=False  # Don't raise exception if docker isn't running
            )
            
            if result.returncode != 0:
                return False, {"error": "Docker daemon is not running"}
            
            return True, {"message": "Docker is running", "version": result.stdout.strip()}
        except Exception as e:
            return False, {"error": str(e)}
    
    def generate_project_id(self):
        """Generate a unique project ID"""
        timestamp = time.strftime("%Y%m%d_%H%M%S")
        random_str = ''.join(random.choices(string.ascii_lowercase + string.digits, k=6))
        return f"website_{timestamp}_{random_str}"
    
    def create_react_website(self, name, description, options=None):
        """Create a React website
        
        Args:
            name: Website name
            description: Website description
            options: Additional options
        
        Returns:
            dict: Result of the operation
        """
        if options is None:
            options = {}
        
        # Generate project ID
        project_id = self.generate_project_id()
        project_dir = self.websites_dir / project_id
        
        try:
            # Create project directory
            project_dir.mkdir(exist_ok=True, parents=True)
            
            # Write specification file
            spec_file = project_dir / "specification.json"
            with open(spec_file, "w") as f:
                json.dump({
                    "name": name,
                    "description": description,
                    "type": "react",
                    "options": options,
                    "created_at": time.strftime("%Y-%m-%d %H:%M:%S")
                }, f, indent=2)
            
            # Create Dockerfile
            dockerfile = project_dir / "Dockerfile"
            with open(dockerfile, "w") as f:
                f.write(f"""FROM node:16-alpine

WORKDIR /app

# Create React app
RUN npx create-react-app my-app

WORKDIR /app/my-app

# Expose port
EXPOSE 3000

# Start the app
CMD ["npm", "start"]
""")
            
            # Create docker-compose.yml
            compose_file = project_dir / "docker-compose.yml"
            with open(compose_file, "w") as f:
                f.write(f"""version: '3'

services:
  website:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/my-app/src
    environment:
      - NODE_ENV=development
""")
            
            # Create src directory
            src_dir = project_dir / "src"
            src_dir.mkdir(exist_ok=True, parents=True)
            
            # Create App.js
            app_js = src_dir / "App.js"
            with open(app_js, "w") as f:
                f.write(f"""import React from 'react';
import './App.css';

function App() {{
  return (
    <div className="App">
      <header className="App-header">
        <h1>{name}</h1>
        <p>{description}</p>
      </header>
      <main>
        <section>
          <h2>About Us</h2>
          <p>This is a website generated by Nexus AI.</p>
        </section>
      </main>
      <footer>
        <p>&copy; {time.strftime("%Y")} {name}. All rights reserved.</p>
      </footer>
    </div>
  );
}}

export default App;
""")
            
            # Create App.css
            app_css = src_dir / "App.css"
            with open(app_css, "w") as f:
                f.write(f"""
.App {{
  text-align: center;
}}

.App-header {{
  background-color: #282c34;
  min-height: 30vh;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  font-size: calc(10px + 2vmin);
  color: white;
  padding: 2rem;
}}

main {{
  max-width: 800px;
  margin: 0 auto;
  padding: 2rem;
}}

section {{
  margin-bottom: 2rem;
}}

footer {{
  background-color: #f5f5f5;
  padding: 1rem;
  text-align: center;
}}
""")
            
            # Build the Docker image
            print(f"Building Docker image for {project_id}...")
            # Uncomment the following to actually build the Docker image
            # subprocess.run(
            #     [self.docker_path, "compose", "-f", str(compose_file), "build"],
            #     cwd=str(project_dir),
            #     check=True
            # )
            
            # Start the container
            print(f"Starting container for {project_id}...")
            # Uncomment the following to actually start the container
            # subprocess.run(
            #     [self.docker_path, "compose", "-f", str(compose_file), "up", "-d"],
            #     cwd=str(project_dir),
            #     check=True
            # )
            
            # Store container info
            self.active_containers[project_id] = {
                "type": "react",
                "directory": str(project_dir),
                "created_at": time.strftime("%Y-%m-%d %H:%M:%S"),
                "url": f"http://localhost:3000"  # This would be the actual URL
            }
            
            return {
                "status": "success",
                "message": f"React website created successfully",
                "project_id": project_id,
                "directory": str(project_dir),
                "url": f"http://localhost:3000",  # This would be the actual URL
                "note": "Docker build commented out for demo purposes"
            }
            
        except Exception as e:
            error_msg = f"Error creating React website: {str(e)}"
            print(error_msg)
            traceback.print_exc()
            
            # Clean up if needed
            if project_dir.exists():
                try:
                    shutil.rmtree(project_dir)
                except Exception:
                    pass
            
            return {
                "status": "error",
                "message": error_msg
            }
    
    def create_static_website(self, name, description, pages=None, options=None):
        """Create a static website
        
        Args:
            name: Website name
            description: Website description
            pages: List of pages to create
            options: Additional options
        
        Returns:
            dict: Result of the operation
        """
        if pages is None:
            pages = ["home", "about", "contact"]
        
        if options is None:
            options = {}
        
        # Generate project ID
        project_id = self.generate_project_id()
        project_dir = self.websites_dir / project_id
        
        try:
            # Create project directory
            project_dir.mkdir(exist_ok=True, parents=True)
            
            # Write specification file
            spec_file = project_dir / "specification.json"
            with open(spec_file, "w") as f:
                json.dump({
                    "name": name,
                    "description": description,
                    "type": "static",
                    "pages": pages,
                    "options": options,
                    "created_at": time.strftime("%Y-%m-%d %H:%M:%S")
                }, f, indent=2)
            
            # Create Dockerfile
            dockerfile = project_dir / "Dockerfile"
            with open(dockerfile, "w") as f:
                f.write(f"""FROM nginx:alpine

COPY ./html /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
""")
            
            # Create docker-compose.yml
            compose_file = project_dir / "docker-compose.yml"
            with open(compose_file, "w") as f:
                f.write(f"""version: '3'

services:
  website:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html
""")
            
            # Create html directory
            html_dir = project_dir / "html"
            html_dir.mkdir(exist_ok=True, parents=True)
            
            # Create CSS directory
            css_dir = html_dir / "css"
            css_dir.mkdir(exist_ok=True, parents=True)
            
            # Create CSS file
            css_file = css_dir / "style.css"
            with open(css_file, "w") as f:
                f.write(f"""
/* Base styles */
* {{
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}}

body {{
    font-family: 'Arial', sans-serif;
    line-height: 1.6;
    color: #333;
    background-color: #f8f9fa;
}}

/* Header */
header {{
    background-color: #343a40;
    color: white;
    padding: 2rem 0;
    text-align: center;
}}

.container {{
    max-width: 1200px;
    margin: 0 auto;
    padding: 0 1rem;
}}

nav {{
    display: flex;
    justify-content: center;
    margin-top: 1rem;
}}

nav ul {{
    display: flex;
    list-style: none;
}}

nav li {{
    margin: 0 1rem;
}}

nav a {{
    color: white;
    text-decoration: none;
    padding: 0.5rem;
}}

nav a:hover {{
    text-decoration: underline;
}}

/* Main content */
main {{
    padding: 2rem 0;
}}

section {{
    margin-bottom: 2rem;
}}

h1, h2, h3 {{
    margin-bottom: 1rem;
}}

p {{
    margin-bottom: 1rem;
}}

/* Footer */
footer {{
    background-color: #343a40;
    color: white;
    text-align: center;
    padding: 1rem 0;
    margin-top: 2rem;
}}

/* Responsive */
@media (max-width: 768px) {{
    nav ul {{
        flex-direction: column;
        align-items: center;
    }}
    
    nav li {{
        margin: 0.5rem 0;
    }}
}}
""")
            
            # Create index.html
            index_file = html_dir / "index.html"
            with open(index_file, "w") as f:
                f.write(f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{name} - Home</title>
    <link rel="stylesheet" href="css/style.css">
</head>
<body>
    <header>
        <div class="container">
            <h1>{name}</h1>
            <p>{description}</p>
            <nav>
                <ul>
                    <li><a href="index.html">Home</a></li>
                    <li><a href="about.html">About</a></li>
                    <li><a href="contact.html">Contact</a></li>
                </ul>
            </nav>
        </div>
    </header>
    
    <main class="container">
        <section>
            <h2>Welcome to {name}</h2>
            <p>This is a website generated by Nexus AI.</p>
        </section>
        
        <section>
            <h2>Our Services</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam auctor, nisl eget ultricies aliquam, quam urna ultricies nisl, eget ultricies nisl nunc eget nisl.</p>
        </section>
    </main>
    
    <footer>
        <div class="container">
            <p>&copy; {time.strftime("%Y")} {name}. All rights reserved.</p>
        </div>
    </footer>
</body>
</html>
""")
            
            # Create about.html
            about_file = html_dir / "about.html"
            with open(about_file, "w") as f:
                f.write(f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{name} - About</title>
    <link rel="stylesheet" href="css/style.css">
</head>
<body>
    <header>
        <div class="container">
            <h1>{name}</h1>
            <p>{description}</p>
            <nav>
                <ul>
                    <li><a href="index.html">Home</a></li>
                    <li><a href="about.html">About</a></li>
                    <li><a href="contact.html">Contact</a></li>
                </ul>
            </nav>
        </div>
    </header>
    
    <main class="container">
        <section>
            <h2>About Us</h2>
            <p>This is a website generated by Nexus AI.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam auctor, nisl eget ultricies aliquam, quam urna ultricies nisl, eget ultricies nisl nunc eget nisl.</p>
        </section>
        
        <section>
            <h2>Our Team</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam auctor, nisl eget ultricies aliquam, quam urna ultricies nisl, eget ultricies nisl nunc eget nisl.</p>
        </section>
    </main>
    
    <footer>
        <div class="container">
            <p>&copy; {time.strftime("%Y")} {name}. All rights reserved.</p>
        </div>
    </footer>
</body>
</html>
""")
            
            # Create contact.html
            contact_file = html_dir / "contact.html"
            with open(contact_file, "w") as f:
                f.write(f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{name} - Contact</title>
    <link rel="stylesheet" href="css/style.css">
</head>
<body>
    <header>
        <div class="container">
            <h1>{name}</h1>
            <p>{description}</p>
            <nav>
                <ul>
                    <li><a href="index.html">Home</a></li>
                    <li><a href="about.html">About</a></li>
                    <li><a href="contact.html">Contact</a></li>
                </ul>
            </nav>
        </div>
    </header>
    
    <main class="container">
        <section>
            <h2>Contact Us</h2>
            <p>Please fill out the form below to get in touch with us.</p>
            
            <form>
                <div style="margin-bottom: 1rem;">
                    <label for="name" style="display: block; margin-bottom: 0.5rem;">Name</label>
                    <input type="text" id="name" name="name" style="width: 100%; padding: 0.5rem; border: 1px solid #ccc; border-radius: 4px;">
                </div>
                
                <div style="margin-bottom: 1rem;">
                    <label for="email" style="display: block; margin-bottom: 0.5rem;">Email</label>
                    <input type="email" id="email" name="email" style="width: 100%; padding: 0.5rem; border: 1px solid #ccc; border-radius: 4px;">
                </div>
                
                <div style="margin-bottom: 1rem;">
                    <label for="message" style="display: block; margin-bottom: 0.5rem;">Message</label>
                    <textarea id="message" name="message" rows="5" style="width: 100%; padding: 0.5rem; border: 1px solid #ccc; border-radius: 4px;"></textarea>
                </div>
                
                <button type="submit" style="background-color: #343a40; color: white; padding: 0.5rem 1rem; border: none; border-radius: 4px; cursor: pointer;">Send Message</button>
            </form>
        </section>
    </main>
    
    <footer>
        <div class="container">
            <p>&copy; {time.strftime("%Y")} {name}. All rights reserved.</p>
        </div>
    </footer>
</body>
</html>
""")
            
            # Build the Docker image
            print(f"Building Docker image for {project_id}...")
            # Uncomment the following to actually build the Docker image
            # subprocess.run(
            #     [self.docker_path, "compose", "-f", str(compose_file), "build"],
            #     cwd=str(project_dir),
            #     check=True
            # )
            
            # Start the container
            print(f"Starting container for {project_id}...")
            # Uncomment the following to actually start the container
            # subprocess.run(
            #     [self.docker_path, "compose", "-f", str(compose_file), "up", "-d"],
            #     cwd=str(project_dir),
            #     check=True
            # )
            
            # Store container info
            self.active_containers[project_id] = {
                "type": "static",
                "directory": str(project_dir),
                "created_at": time.strftime("%Y-%m-%d %H:%M:%S"),
                "url": f"http://localhost:8080"  # This would be the actual URL
            }
            
            return {
                "status": "success",
                "message": f"Static website created successfully",
                "project_id": project_id,
                "directory": str(project_dir),
                "url": f"http://localhost:8080",  # This would be the actual URL
                "note": "Docker build commented out for demo purposes"
            }
            
        except Exception as e:
            error_msg = f"Error creating static website: {str(e)}"
            print(error_msg)
            traceback.print_exc()
            
            # Clean up if needed
            if project_dir.exists():
                try:
                    shutil.rmtree(project_dir)
                except Exception:
                    pass
            
            return {
                "status": "error",
                "message": error_msg
            }
    
    def stop_container(self, project_id):
        """Stop a container
        
        Args:
            project_id: Project ID
        
        Returns:
            dict: Result of the operation
        """
        if project_id not in self.active_containers:
            return {
                "status": "error",
                "message": f"Project {project_id} not found"
            }
        
        try:
            project_dir = self.active_containers[project_id]["directory"]
            compose_file = Path(project_dir) / "docker-compose.yml"
            
            if compose_file.exists():
                # Stop the container
                subprocess.run(
                    [self.docker_path, "compose", "-f", str(compose_file), "down"],
                    cwd=project_dir,
                    check=True
                )
            
            # Remove from active containers
            del self.active_containers[project_id]
            
            return {
                "status": "success",
                "message": f"Container for project {project_id} stopped"
            }
        except Exception as e:
            error_msg = f"Error stopping container for project {project_id}: {str(e)}"
            print(error_msg)
            
            return {
                "status": "error",
                "message": error_msg
            }
    
    def list_active_containers(self):
        """List active containers
        
        Returns:
            list: List of active containers
        """
        return self.active_containers


# For testing the Docker integration
if __name__ == "__main__":
    # Test Docker integration
    print("Testing Docker integration...")
    docker_builder = DockerWebsiteBuilder()
    docker_status, docker_info = docker_builder.check_docker()
    
    if docker_status:
        print("Docker is running!")
        
        # Test static website creation
        print("\nCreating a static website...")
        result = docker_builder.create_static_website(
            name="Test Website",
            description="A test website created by DockerWebsiteBuilder"
        )
        
        if result["status"] == "success":
            print("Static website created successfully!")
            print(f"Project ID: {result['project_id']}")
            print(f"Directory: {result['directory']}")
            print(f"URL: {result['url']}")
            
            # Test React website creation
            print("\nCreating a React website...")
            result = docker_builder.create_react_website(
                name="Test React Website",
                description="A test React website created by DockerWebsiteBuilder"
            )
            
            if result["status"] == "success":
                print("React website created successfully!")
                print(f"Project ID: {result['project_id']}")
                print(f"Directory: {result['directory']}")
                print(f"URL: {result['url']}")
                
                # List active containers
                print("\nActive containers:")
                active_containers = docker_builder.list_active_containers()
                for project_id, container in active_containers.items():
                    print(f"- {project_id}: {container['type']} ({container['url']})")
            else:
                print(f"Failed to create React website: {result['message']}")
        else:
            print(f"Failed to create static website: {result['message']}")
    else:
        print(f"Docker is not running: {docker_info['error']}")
